// H1 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    level._id_058F["dust_ambient_interior_big"] = loadfx( "vfx/map/greece/dust_ambient_interior_big" );
    level._id_058F["elec_sparks__blue_runner"] = loadfx( "vfx/explosion/elec_sparks__blue_runner" );
    level._id_058F["smoldering_smk_ground_bog_b"] = loadfx( "vfx/smoke/smoldering_smk_ground_bog_b" );
    level._id_058F["bog_b"] = loadfx( "vfx/lensflare/bog_b" );
    level._id_058F["smoke_window_slow_fb"] = loadfx( "vfx/smoke/smoke_window_slow_fb" );
    level._id_058F["smoke_window_slow_fb_sm"] = loadfx( "vfx/smoke/smoke_window_slow_fb_sm" );
    level._id_058F["embers_constant_sm"] = loadfx( "vfx/fire/embers_constant_sm" );
    level._id_058F["ripple_rings_bog"] = loadfx( "vfx/water/ripple_rings_bog" );
    level._id_058F["water_drips_bog_ripples"] = loadfx( "vfx/rain/water_drips_bog_ripples" );
    level._id_058F["sewage_flies_flying_bog"] = loadfx( "vfx/map/mp_clowntown/sewage_flies_flying_bog" );
    level._id_058F["brg_dust_mote_ambient_interior"] = loadfx( "vfx/map/mp_zombie_brg/brg_dust_mote_ambient_interior" );
    level._id_058F["fire_wreckage_ground"] = loadfx( "vfx/fire/ground_fire_mwr" );
    level._id_058F["fire_wreckage_large"] = loadfx( "vfx/fire/ground_fire_large_mwr" );
    level._id_058F["fire_dumpster"] = loadfx( "vfx/fire/dumpster_fire_mwr_bog_b" );
    level._id_058F["fire_window"] = loadfx( "vfx/fire/window_fire_mwr_bog_b" );
    level._id_058F["smoke_pillar_black_lrg_slow_fb"] = loadfx( "vfx/smoke/smoke_pillar_black_lrg_slow_fb" );
    level._id_058F["ash_falling"] = loadfx( "fx/misc/ash_falling" );
    level._id_058F["ash_falling_narrow"] = loadfx( "fx/misc/ash_falling_narrow" );
    level._id_058F["floating_room_dust_02"] = loadfx( "fx/misc/floating_room_dust_02" );
    level._id_058F["battlefield_smokebank_S"] = loadfx( "fx/smoke/battlefield_smokebank_S" );
    level._id_058F["battlefield_smokebank_S_far"] = loadfx( "fx/smoke/battlefield_smokebank_S_far" );
    level._id_058F["battlefield_smokebank_S_thin"] = loadfx( "fx/smoke/battlefield_smokebank_S_thin" );
    level._id_058F["thin_black_smoke_M"] = loadfx( "fx/smoke/thin_black_smoke_M" );
    level._id_058F["thin_black_smoke_M_far"] = loadfx( "fx/smoke/thin_black_smoke_M_far" );
    level._id_058F["thin_black_smoke_L"] = loadfx( "fx/smoke/thin_black_smoke_L" );
    level._id_058F["thick_black_smoke_M"] = loadfx( "fx/smoke/thick_black_smoke_M" );
    level._id_058F["thick_black_smoke_bogb_end"] = loadfx( "fx/smoke/thick_black_smoke_bogb_end" );
    level._id_058F["dust_wind_slow"] = loadfx( "fx/dust/dust_wind_slow_yel_loop" );
    level._id_058F["village_window_morning_fog"] = loadfx( "fx/smoke/village_window_morning_fog" );
    level._id_058F["village_window_morning_fog_close"] = loadfx( "fx/smoke/village_window_morning_fog_close" );
    level._id_058F["village_window_morning_fog_big"] = loadfx( "fx/smoke/village_window_morning_fog_big" );
    level._id_058F["village_window_morning_fog_big_thick"] = loadfx( "fx/smoke/village_window_morning_fog_big_thick" );
    level._id_058F["village_window_morning_fog_flat"] = loadfx( "fx/smoke/village_window_morning_fog_flat" );
    level._id_058F["smk_stacks_lp_lrg_a_nofog"] = loadfx( "vfx/smoke/dlc/smk_stacks_lp_lrg_a_nofog" );
    level._id_058F["battlefield_smoke_m_slow"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_m_slow_bog_b" );
    level._id_058F["battlefield_smoke_m_slow_busback"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_m_slow_busback" );
    level._id_058F["battlefield_smoke_m_slow_thin"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_m_slow_thin" );
    level._id_058F["battlefield_smoke_shadow"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_shadow" );
    level._id_058F["battlefield_smoke_shadow_small"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_shadow_small" );
    level._id_058F["smk_low_linger_narrow_runner"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_runner" );
    level._id_058F["smk_low_linger_narrow_slow"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_slow" );
    level._id_058F["smk_low_linger_narrow_slow_dark"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_slow_dark" );
    level._id_058F["smk_low_linger_narrow_slow_nolit"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_slow_nolit" );
    level._id_058F["smk_low_linger_narrow_slow_nolit_win"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_slow_nolit_win" );
    level._id_058F["smk_low_linger_narrow_slow_nolit_bus"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_slow_nolit_bus" );
    level._id_058F["smk_low_linger_narrow_nolit_slow"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_nolit_slow" );
    level._id_058F["smk_low_linger_narrow_less"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_less" );
    level._id_058F["smk_low_linger_narrow_nolit_less"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_nolit_less" );
    level._id_058F["smk_low_linger_narrow_nolit_far"] = loadfx( "vfx/smoke/dlc/smk_low_linger_narrow_nolit_far" );
    level._id_058F["heat_distortion_mirage_large"] = loadfx( "vfx/distortion/heat_distortion_mirage_large" );
    level._id_058F["dust_falling_ceiling_light"] = loadfx( "vfx/dust/dust_falling_ceiling_light" );
    level._id_058F["dust_falling_ceiling_light_runner"] = loadfx( "vfx/dust/dust_falling_ceiling_light_runner" );
    level._id_058F["fog_ceiling_static"] = loadfx( "vfx/fog/fog_ceiling_static" );
    level._id_058F["paper_sheet_01_blowing"] = loadfx( "vfx/wind/paper_sheet_01_blowing" );
    level._id_058F["fluorescent_light_cone"] = loadfx( "vfx/lights/ca/fluorescent_light_cone" );
    level._id_058F["fluorescent_light_cone_thick"] = loadfx( "vfx/lights/ca/fluorescent_light_cone_thick" );
    level._id_058F["fluorescent_light_cone_flat"] = loadfx( "vfx/lights/ca/fluorescent_light_cone_flat" );
    level._id_058F["round_glow_lightbulb"] = loadfx( "vfx/lights/ca/round_glow_lightbulb" );
    level._id_058F["ash_screen"] = loadfx( "vfx/ash/ash_screen" );
    level._id_058F["bog_b_vl_a"] = loadfx( "fx/misc/bog_b_vl_a" );
    level._id_058F["fog_facing"] = loadfx( "vfx/fog/fog_facing" );
    level._id_058F["00_particle_shadow_animated_lrg_e"] = loadfx( "vfx/cloud/00_particle_shadow_animated_lrg_e" );
    level._id_058F["00_particle_shadow_animated_med_e"] = loadfx( "vfx/cloud/00_particle_shadow_animated_med_e" );
    level._id_058F["00_particle_shadow_animated_sm_e"] = loadfx( "vfx/cloud/00_particle_shadow_animated_sm_e" );
    level._id_058F["00_particle_shadow_static_lrg_e"] = loadfx( "vfx/cloud/00_particle_shadow_static_lrg_e" );
    level._id_058F["00_particle_shadow_static_med_e"] = loadfx( "vfx/cloud/00_particle_shadow_static_med_e" );
    level._id_058F["00_particle_shadow_static_sm_e"] = loadfx( "vfx/cloud/00_particle_shadow_static_sm_e" );
    level._id_058F["mortar"]["dirt"] = loadfx( "fx/explosions/grenadeExp_dirt" );
    level._id_058F["mortar"]["mud"] = loadfx( "fx/explosions/grenadeExp_mud" );
    level._id_78BA["mortar"]["incomming"] = "mortar_incoming";
    level._id_78BA["mortar"]["dirt"] = "mortar_explosion_dirt";
    level._id_78BA["mortar"]["mud"] = "mortar_explosion_water";
    level._id_058F["wall_explosion_small"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["wall_explosion_grnd"] = loadfx( "fx/explosions/wall_explosion_grnd" );
    level._id_058F["wall_explosion_draft"] = loadfx( "fx/explosions/wall_explosion_draft" );
    level._id_058F["wall_explosion_round"] = loadfx( "fx/explosions/wall_explosion_round" );
    level._id_058F["wall_explosion_dust"] = loadfx( "fx/explosions/wall_explosion_dust" );
    level._id_058F["tank_round_spark"] = loadfx( "fx/impacts/tank_round_spark" );
    level._id_058F["wall_explosion_blast"] = loadfx( "fx/explosions/wall_explosion_blast" );
    level._id_058F["wall_explosion_center"] = loadfx( "fx/explosions/wall_explosion_bogb_center" );
    level._id_058F["exploder"]["100"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["exploder"]["101"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["exploder"]["102"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["exploder"]["102"] = loadfx( "fx/explosions/wall_explosion_draft" );
    level._id_058F["exploder"]["103"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["exploder"]["104"] = loadfx( "fx/explosions/wall_explosion_small" );
    level._id_058F["exploder"]["105"] = loadfx( "fx/explosions/wall_explosion_grnd" );
    level._id_058F["exploder"]["400"] = loadfx( "fx/explosions/wall_explosion_round" );
    level._id_058F["tv_explosion"] = loadfx( "fx/explosions/tv_explosion" );
    level._id_0685["tankcrush"]["window_med"] = loadfx( "fx/props/car_glass_med_tankcrush" );
    level._id_0685["tankcrush"]["window_large"] = loadfx( "fx/props/car_glass_med_tankcrush_no_exp" );
    level._id_0685["tankcrush"]["window_med_left"] = loadfx( "fx/props/car_glass_med_tankcrush_no_exp" );
    level._id_0685["tankcrush"]["window_med_right"] = loadfx( "fx/props/car_glass_med_tankcrush_no_exp" );
    level._id_0685["tankcrush"]["window_large_back"] = loadfx( "fx/props/car_glass_med_tankcrush" );
    level._id_0685["tankcrush"]["window_large_front"] = loadfx( "fx/props/car_glass_med_tankcrush_no_exp" );
    level._id_058F["mg_kill_grenade"] = loadfx( "fx/explosions/grenadeExp_wood" );
    level._id_78BA["mg_kill_grenade_bounce"] = "grenade_bounce_wood";
    level._id_78BA["mg_kill_grenade_explode"] = "grenade_explode_wood";
    level._id_058F["afterburner"] = loadfx( "fx/fire/jet_afterburner" );
    level._id_058F["contrail"] = loadfx( "fx/smoke/jet_contrail" );
    level._id_058F["contrail_02"] = loadfx( "fx/smoke/jet_contrail_02" );
    level._id_058F["abrams_exhaust"] = loadfx( "fx/distortion/abrams_exhaust" );
    level._id_058F["t72_ammo_breach"] = loadfx( "fx/explosions/tank_ammo_breach_mwr_bog_b" );
    level._id_058F["t72_ammo_explosion"] = loadfx( "fx/explosions/t72_ammo_explosion_mwr_bog_b" );
    level._id_058F["firelp_large_pm"] = loadfx( "fx/fire/firelp_on_t72_mwr_bog_b" );
    animscripts\utility::_id_7F74( "asphalt", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "brick", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "carpet", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "cloth", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "concrete", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "dirt", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "foliage", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "grass", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "metal", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "mud", loadfx( "fx/impacts/footstep_mud" ) );
    animscripts\utility::_id_7F74( "rock", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "sand", loadfx( "fx/impacts/footstep_dust" ) );
    animscripts\utility::_id_7F74( "water", loadfx( "fx/impacts/footstep_water" ) );
    animscripts\utility::_id_7F74( "wood", loadfx( "fx/impacts/footstep_dust" ) );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "brick", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "bark", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "carpet", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "cloth", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "concrete", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "dirt", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "flesh", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "foliage", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "glass", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "grass", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "gravel", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "ice", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "metal", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "mud", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "paper", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "plaster", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "rock", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "sand", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "snow", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "water", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "wood", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "asphalt", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "ceramic", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "plastic", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "rubber", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "cushion", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "fruit", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "painted metal", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "default", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_m1a1_abrams", "none", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "brick", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "bark", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "carpet", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "cloth", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "concrete", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "dirt", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "flesh", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "foliage", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "glass", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "grass", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "gravel", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "ice", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "metal", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "mud", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "paper", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "plaster", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "rock", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "sand", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "snow", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "water", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "wood", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "asphalt", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "ceramic", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "plastic", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "rubber", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "cushion", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "fruit", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "painted metal", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "default", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_t72_tank", "none", "fx/treadfx/tread_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "brick", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "bark", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "carpet", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "cloth", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "concrete", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "dirt", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "flesh", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "foliage", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "glass", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "grass", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "gravel", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "ice", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "metal", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "mud", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "paper", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "plaster", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "rock", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "sand", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "snow", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "water", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "wood", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "asphalt", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "ceramic", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "plastic", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "rubber", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "cushion", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "fruit", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "painted metal", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "default", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_ch46e", "none", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "brick", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "bark", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "carpet", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "cloth", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "concrete", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "dirt", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "flesh", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "foliage", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "glass", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "grass", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "gravel", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "ice", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "metal", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "mud", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "paper", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "plaster", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "rock", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "sand", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "snow", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "water", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "wood", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "asphalt", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "ceramic", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "plastic", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "rubber", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "cushion", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "fruit", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "painted metal", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "default", "fx/treadfx/heli_dust_bog_b" );
    _id_A59D::_id_8350( "script_vehicle_mi17_woodland_fly_cheap", "none", "fx/treadfx/heli_dust_bog_b" );
    maps\createfx\bog_b_fx::main();
    maps\createfx\bog_b_sound::main();
}
